# Generated by Django 4.1.1 on 2022-12-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
